 dist: xenial
 language: cpp
 compiler: clang
 before_script:
         - sudo apt update
         - sudo apt install libspdlog-dev -y
         - sudo apt install libboost-all-dev -y
 script:
         - doxygen Doxyfile
         - cmake .
         - cmake --build .
         - cmake --build . --target package
 deploy:

         provider: pages
         skip_cleanup: true
         github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
         keep_history: true
         on:
           branch: master
         script:
           - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ualexisvabel:$BINTRAY_API_KEY "https://api.bintray.com/content/alexisvabel/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/home/travis/build/AlexisVaBel/otus-cpp-hw_04/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
